name: check_resources
description: Check for available resources on the system.

argument_groups:
  - name: Inputs
    arguments:
      - name: --tmp_space_required
        type: integer
        description: Temporary space required in MB.
        required: false
        default: 1000
      - name: --publish_space_required
        type: integer
        description: Publish space required in MB.
        required: false
        default: 500
      - name: --publish_dir
        type: file
        description: Directory where workflow outputs will be published.
        required: false

  - name: Outputs
    arguments:
      - name: --output
        type: file
        direction: output
        description: Output file containing system resources details.
        required: false
        default: output.txt

resources:
  - type: bash_script
    path: script.sh

test_resources:
  - type: bash_script
    path: test.sh

engines:
  - type: docker
    image: bash:latest

runners:
  - type: executable
  - type: nextflow