name: check_resources
description: Check if resources are available

argument_groups:
  - name: Options
    arguments:
      - name: --req_disk_space
        type: integer
        description: Required disk space percentage.
        required: true
        default: 20

resources:
  - type: bash_script
    path: script.sh

engines:
  - type: docker
    image: bash:latest

runners:
  - type: executable
  - type: nextflow